# Generated by Django 3.2.11 on 2022-02-04 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import global_id.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, error_messages={'unique': 'This GUID already exists.'}, help_text='GUID must start with English letters and contain numbers and one underscore ( _ ). 4-60chars only ', max_length=60, null=True, unique=True, validators=[global_id.models.validators.GUIDValidator(), django.core.validators.MinLengthValidator(4, 'GUID must have at least 4 chars'), django.core.validators.MaxLengthValidator(60, 'GUID can have at last 60 chars')], verbose_name='Global-Unique-ID')),
                ('chat_id', models.PositiveIntegerField()),
                ('chat_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
