# Generated by Django 3.2.11 on 2022-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guid',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
    ]
