# Generated by Django 3.2.12 on 2022-02-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Edited at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is item deleted or not', verbose_name='Is deleted')),
                ('chat_id', models.BigIntegerField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], db_index=True, max_length=10, verbose_name='Content type')),
                ('content_id', models.BigIntegerField()),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is edited')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('chat_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('content_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
