# Generated by Django 3.2.12 on 2022-03-13 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateField(auto_now_add=True, verbose_name='Seen at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_users', to='message.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_messges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
