# Generated by Django 3.2.11 on 2022-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_community_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='used_link',
            new_name='_used_link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_joined_by_guid',
        ),
        migrations.AddField(
            model_name='member',
            name='used_guid',
            field=models.CharField(blank=True, help_text='The guid that member used to join if joined by guid', max_length=60, null=True, verbose_name='Used guid'),
        ),
    ]
