# Generated by Django 3.2.11 on 2022-02-09 13:25

import community.models.utils.link_generator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20220207_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='link',
            field=models.CharField(auto_created=True, db_index=True, default=community.models.utils.link_generator.generate_invite_link, max_length=37, unique=True, validators=[django.core.validators.RegexValidator('^([-])[A-Za-z\\d]{32}([\\d]{4})$')], verbose_name='Invite link'),
        ),
    ]
