# Generated by Django 3.2.11 on 2022-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_edit_invitelink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is item deleted or not', verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is item deleted or not', verbose_name='Is deleted'),
        ),
    ]
