# Generated by Django 3.2.10 on 2022-01-10 01:06

import auth_app.models.verify
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypt_decrypt_fields.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_delete_access_verifycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_code', encrypt_decrypt_fields.django_fields.EncryptedBinaryField(auto_created=True, db_index=True, default=auth_app.models.verify.VerifyCode.generate_code, verbose_name='Code')),
                ('token', models.CharField(auto_created=True, db_index=True, max_length=128, null=True, verbose_name='Token')),
                ('is_token_expired', models.BooleanField(default=False, help_text='Token is expired or not')),
                ('_tries', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(auto_created=True, db_index=True, max_length=128, null=True, verbose_name='Token')),
                ('is_token_expired', models.BooleanField(default=False, help_text='Token is expired or not')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this token used', null=True, verbose_name='Last used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='user.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
