# Generated by Django 3.2.11 on 2022-01-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_conv_alias_pin_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_deleted',
        ),
    ]
