# Generated by Django 3.2.11 on 2022-02-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_remove_conversation_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
    ]
