# Generated by Django 3.2.10 on 2021-12-14 23:33

from django.db import migrations, models
import django.db.models.deletion
import encrypt_decrypt_fields.django_fields
import picturic.fields
import picturic.utils
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211213_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='email',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='_code',
            field=encrypt_decrypt_fields.django_fields.EncryptedBinaryField(auto_created=True, db_index=True, default=user.models.VerifyCode.generate_code, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
