# Generated by Django 3.2.10 on 2022-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_verify_add_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='is_token_expired',
            field=models.BooleanField(default=False, help_text='Token is expired or not'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_token_expired',
            field=models.BooleanField(default=False, help_text='Token is expired or not'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='is_token_expired',
            field=models.BooleanField(default=False, help_text='Token is expired or not'),
        ),
    ]
