# Generated by Django 3.2.10 on 2022-01-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_is_token_expired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
    ]
